frontend:
    @echo Installing Frontend.
mongodb:
    @echo Installing Catalogue.
catalogue:
    @echo Installing Catalogue.
cart:
    @echo Installing Cart.
user:
    @echo Installing User.
shipping:
    @echo Installing Shipping.
payment:
    @echo Installing Payment.
redis:
    @echo Installing Redis.
mysql:
    @echo Installing mysql.
rabbitmq:
    @echo Installing Rabbitmq.






frontend:
    @echo Installing Frontend.